SET IDENTITY_INSERT [dbo].[Users] ON
INSERT INTO [dbo].[Users] ([User_ID], [First_Name], [Last_Name], [Gender], [Post_Code], [City], [District], [Street], [Email], [Phone], [User_Name], [Password], [Last_Active], [Last_LoginIP], [Secret_Qustion], [Register_Date]) VALUES (1, N'Marwan', N'Diab', N'Male', NULL, N'Qena', N'Dishna', N'bhr', N'marawan.diab', N'01026252078', N'Marwan', N'111', NULL, NULL, N'', NULL)
INSERT INTO [dbo].[Users] ([User_ID], [First_Name], [Last_Name], [Gender], [Post_Code], [City], [District], [Street], [Email], [Phone], [User_Name], [Password], [Last_Active], [Last_LoginIP], [Secret_Qustion], [Register_Date]) VALUES (2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'diab0.khaled@gmail.com', NULL, N'diaboo', N'P@ssw0rd', NULL, NULL, NULL, N'2020-08-11')
INSERT INTO [dbo].[Users] ([User_ID], [First_Name], [Last_Name], [Gender], [Post_Code], [City], [District], [Street], [Email], [Phone], [User_Name], [Password], [Last_Active], [Last_LoginIP], [Secret_Qustion], [Register_Date]) VALUES (3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'diab0.khaled@gmail.com', NULL, N'diaboo', N'P@ssw0rd', NULL, NULL, NULL, N'2020-08-11')
INSERT INTO [dbo].[Users] ([User_ID], [First_Name], [Last_Name], [Gender], [Post_Code], [City], [District], [Street], [Email], [Phone], [User_Name], [Password], [Last_Active], [Last_LoginIP], [Secret_Qustion], [Register_Date]) VALUES (4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'z3ma0.adel@gmail.com', NULL, N'z3ma', N'123', NULL, NULL, NULL, N'2020-08-11')
INSERT INTO [dbo].[Users] ([User_ID], [First_Name], [Last_Name], [Gender], [Post_Code], [City], [District], [Street], [Email], [Phone], [User_Name], [Password], [Last_Active], [Last_LoginIP], [Secret_Qustion], [Register_Date]) VALUES (5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'sasa@gmail.com', NULL, N'sasa', N'12345', NULL, NULL, NULL, N'2020-08-11')
INSERT INTO [dbo].[Users] ([User_ID], [First_Name], [Last_Name], [Gender], [Post_Code], [City], [District], [Street], [Email], [Phone], [User_Name], [Password], [Last_Active], [Last_LoginIP], [Secret_Qustion], [Register_Date]) VALUES (6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'aly0.moody@gmail.com', NULL, N'aly', N'555', NULL, NULL, NULL, N'2020-08-11')
INSERT INTO [dbo].[Users] ([User_ID], [First_Name], [Last_Name], [Gender], [Post_Code], [City], [District], [Street], [Email], [Phone], [User_Name], [Password], [Last_Active], [Last_LoginIP], [Secret_Qustion], [Register_Date]) VALUES (7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'moody@gmail.com', NULL, N'moody', N'777', NULL, NULL, NULL, N'2020-08-11')
INSERT INTO [dbo].[Users] ([User_ID], [First_Name], [Last_Name], [Gender], [Post_Code], [City], [District], [Street], [Email], [Phone], [User_Name], [Password], [Last_Active], [Last_LoginIP], [Secret_Qustion], [Register_Date]) VALUES (8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'mostafa.osama@gmail.com', NULL, N'mostafa', N'1234', NULL, NULL, NULL, N'2020-08-11')
SET IDENTITY_INSERT [dbo].[Users] OFF
